#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TwinTechsFormsExample.Droid.Resource", IsApplication=true)]

namespace TwinTechsFormsExample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::TwinTechsFormsExample.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::TwinTechsFormsExample.Droid.Resource.String.Hello;
			global::TwinTechsLib.Droid.Resource.Attribute.layoutManager = global::TwinTechsFormsExample.Droid.Resource.Attribute.layoutManager;
			global::TwinTechsLib.Droid.Resource.Attribute.reverseLayout = global::TwinTechsFormsExample.Droid.Resource.Attribute.reverseLayout;
			global::TwinTechsLib.Droid.Resource.Attribute.spanCount = global::TwinTechsFormsExample.Droid.Resource.Attribute.spanCount;
			global::TwinTechsLib.Droid.Resource.Attribute.stackFromEnd = global::TwinTechsFormsExample.Droid.Resource.Attribute.stackFromEnd;
			global::TwinTechsLib.Droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::TwinTechsFormsExample.Droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::TwinTechsLib.Droid.Resource.Id.item_touch_helper_previous_elevation = global::TwinTechsFormsExample.Droid.Resource.Id.item_touch_helper_previous_elevation;
			global::TwinTechsLib.Droid.Resource.String.ApplicationName = global::TwinTechsFormsExample.Droid.Resource.String.ApplicationName;
			global::TwinTechsLib.Droid.Resource.String.Hello = global::TwinTechsFormsExample.Droid.Resource.String.Hello;
			global::TwinTechsLib.Droid.Resource.String.library_name = global::TwinTechsFormsExample.Droid.Resource.String.library_name;
			global::TwinTechsLib.Droid.Resource.Styleable.RecyclerView = global::TwinTechsFormsExample.Droid.Resource.Styleable.RecyclerView;
			global::TwinTechsLib.Droid.Resource.Styleable.RecyclerView_android_orientation = global::TwinTechsFormsExample.Droid.Resource.Styleable.RecyclerView_android_orientation;
			global::TwinTechsLib.Droid.Resource.Styleable.RecyclerView_layoutManager = global::TwinTechsFormsExample.Droid.Resource.Styleable.RecyclerView_layoutManager;
			global::TwinTechsLib.Droid.Resource.Styleable.RecyclerView_reverseLayout = global::TwinTechsFormsExample.Droid.Resource.Styleable.RecyclerView_reverseLayout;
			global::TwinTechsLib.Droid.Resource.Styleable.RecyclerView_spanCount = global::TwinTechsFormsExample.Droid.Resource.Styleable.RecyclerView_spanCount;
			global::TwinTechsLib.Droid.Resource.Styleable.RecyclerView_stackFromEnd = global::TwinTechsFormsExample.Droid.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130903040;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_previous_elevation = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
